# NYC Taxi ETA Prediction
# Week 03 - Production Grade Regression Benchmark
# Notebook 01: Data Audit

In [10]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [11]:
import importlib
import src.data.load_data as ld

importlib.reload(ld)

print(ld.RAW_DATA_PATH)
print((ld.RAW_DATA_PATH / "yellow_tripdata_2023-01.parquet").exists())

Project Root: C:\Users\abuba\Downloads\ML-Projects\Day-5
Raw Data Path: C:\Users\abuba\Downloads\ML-Projects\Day-5\data\raw
C:\Users\abuba\Downloads\ML-Projects\Day-5\data\raw
True

In [12]:
import pandas as pd
import numpy as np

from pathlib import Path
import sys

PROJECT_ROOT = Path("..").resolve()
sys.path.append(str(PROJECT_ROOT))

from src.data.load_data import *
from src.data.validate_data import *

## Load Dataset

In [13]:
from pathlib import Path

RAW_DIR = Path.cwd().parent / "data" / "raw"

print("Raw directory:")
for item in RAW_DIR.iterdir():
    print("-", item.name)

print("\nTaxi Zone directory:")
for item in (RAW_DIR / "taxi_zones").iterdir():
    print("-", item.name)

Raw directory:
- taxi_zones
- taxi_zone_lookup.csv
- yellow_tripdata_2023-01.parquet
- yellow_tripdata_2023-02.parquet
- yellow_tripdata_2023-03.parquet
- yellow_tripdata_2023-04.parquet
- yellow_tripdata_2023-05.parquet
- yellow_tripdata_2023-06.parquet
- yellow_tripdata_2023-07.parquet

Taxi Zone directory:
- taxi_zones.dbf
- taxi_zones.prj
- taxi_zones.sbn
- taxi_zones.sbx
- taxi_zones.shp
- taxi_zones.shp.xml
- taxi_zones.shx

In [15]:
taxi_df = load_all_months()

zone_df = load_zone_lookup()

In [16]:
print(taxi_df.shape)
print(zone_df.shape)

(19493620, 20)
(265, 4)

In [17]:
taxi_df.head(8)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,NaN
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,NaN
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,NaN
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,NaN
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,NaN
5,2,2023-01-01 00:50:34,2023-01-01 01:02:52,1.0,1.84,1.0,N,161,137,1,12.8,1.00,0.5,10.00,0.0,1.0,27.80,2.5,0.00,NaN
6,2,2023-01-01 00:09:22,2023-01-01 00:19:49,1.0,1.66,1.0,N,239,143,1,12.1,1.00,0.5,3.42,0.0,1.0,20.52,2.5,0.00,NaN
7,2,2023-01-01 00:27:12,2023-01-01 00:49:56,1.0,11.70,1.0,N,142,200,1,45.7,1.00,0.5,10.74,3.0,1.0,64.44,2.5,0.00,NaN

In [18]:
taxi_df.tail()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,Airport_fee
19493615,2,2023-06-30 23:30:21,2023-07-01 00:00:46,NaN,9.20,NaN,NaN,42,148,0,38.53,0.00,0.5,8.51,0.00,1.0,51.04,NaN,NaN,NaN
19493616,1,2023-06-30 23:34:22,2023-07-01 00:32:59,NaN,20.20,NaN,NaN,132,74,0,70.00,1.75,0.5,11.97,6.55,1.0,91.77,NaN,NaN,NaN
19493617,2,2023-06-30 23:45:00,2023-07-01 00:10:00,NaN,6.16,NaN,NaN,256,140,0,28.03,0.00,0.5,6.41,0.00,1.0,38.44,NaN,NaN,NaN
19493618,2,2023-06-30 23:13:38,2023-06-30 23:51:19,NaN,11.65,NaN,NaN,91,246,0,45.74,0.00,0.5,0.00,6.55,1.0,56.29,NaN,NaN,NaN
19493619,2,2023-06-30 23:18:00,2023-06-30 23:31:00,NaN,1.40,NaN,NaN,164,230,0,14.35,0.00,0.5,0.00,0.00,1.0,18.35,NaN,NaN,NaN

In [19]:
zone_df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [20]:
dataset_summary(taxi_df)

============================================================
Rows    : 19,493,620
Columns : 20
============================================================
Duplicate Rows
0
============================================================
Missing Values
airport_fee              16498597
Airport_fee               3523575
passenger_count            528552
RatecodeID                 528552
congestion_surcharge       528552
store_and_fwd_flag         528552
VendorID                        0
tpep_pickup_datetime            0
tpep_dropoff_datetime           0
DOLocationID                    0
trip_distance                   0
PULocationID                    0
extra                           0
fare_amount                     0
payment_type                    0
mta_tax                         0
improvement_surcharge           0
tolls_amount                    0
tip_amount                      0
total_amount                    0
dtype: int64

In [22]:
show_columns(taxi_df)

['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee', 'Airport_fee']

In [23]:
check_dtypes(taxi_df)

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
Airport_fee                     float64
dtype: object

In [24]:
taxi_df.describe(include="object").T

C:\Users\abuba\AppData\Local\Temp\ipykernel_2172\2188050421.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  taxi_df.describe(include="object").T

                       count unique top      freq
store_and_fwd_flag  18965068      2   N  18854960

In [25]:
missing = taxi_df.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

airport_fee             16498597
Airport_fee              3523575
passenger_count           528552
RatecodeID                528552
congestion_surcharge      528552
store_and_fwd_flag        528552
dtype: int64

In [26]:
memory_mb = taxi_df.memory_usage(deep=True).sum() / 1024**2

print(f"Memory Usage: {memory_mb:.2f} MB")

Memory Usage: 2994.90 MB

Timestamp Range

In [28]:
print("Pickup Time Range")
print(taxi_df["tpep_pickup_datetime"].min())
print(taxi_df["tpep_pickup_datetime"].max())

print()

print("Dropoff Time Range")
print(taxi_df["tpep_dropoff_datetime"].min())
print(taxi_df["tpep_dropoff_datetime"].max())

Pickup Time Range
2001-01-01 00:06:49
2023-09-05 18:20:48

Dropoff Time Range
2001-01-01 00:16:31
2023-09-05 18:24:21

In [29]:
# Passenger Count Distribution
taxi_df["passenger_count"].value_counts().sort_index()

passenger_count
0.0      327712
1.0    14304756
2.0     2839892
3.0      699944
4.0      367080
5.0      257985
6.0      167550
7.0          34
8.0          90
9.0          25
Name: count, dtype: int64

In [30]:
#Vendor Distribution
taxi_df["VendorID"].value_counts()

VendorID
2    14242526
1     5245998
6        5096
Name: count, dtype: int64

## Initial Findings

- Successfully loaded January–June 2023 taxi trip data.
- Taxi Zone Lookup loaded successfully.
- Dataset schema verified.
- Timestamp columns identified.
- Missing values identified.
- Duplicate rows checked.
- Passenger count distribution reviewed.
- Data cleaning has **not** been performed yet.
- Feature engineering has **not** been performed yet.
- Target variable (`trip_duration_minutes`) has **not** been created yet.

### Next Step

Create a reusable preprocessing pipeline in `src/data/build_dataset.py` to:

- Create target variable
- Remove invalid trips
- Remove outliers
- Remove leakage columns
- Save cleaned dataset